# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://mfqxurkbydpaysvmrips.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mcXh1cmtieWRwYXlzdm1yaXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM1NjA1NTgsImV4cCI6MjAzOTEzNjU1OH0.FVgcVeCfsjAETraIMrZC6S18wr_P2wYs6uYkstYGWiY"
